"""fix_columns

Revision ID: c6c075ee218d
Revises: 543a7870e015
Create Date: 2025-06-10 21:49:24.442990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c075ee218d'
down_revision: Union[str, None] = '543a7870e015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_channels_title'), 'channels', ['title'], unique=False)
    op.create_index(op.f('ix_channels_url'), 'channels', ['url'], unique=False)
    op.create_index(op.f('ix_channels_username'), 'channels', ['username'], unique=True)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_permission_level'), 'roles', ['permission_level'], unique=False)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.drop_index(op.f('ix_roles_permission_level'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_channels_username'), table_name='channels')
    op.drop_index(op.f('ix_channels_url'), table_name='channels')
    op.drop_index(op.f('ix_channels_title'), table_name='channels')
    # ### end Alembic commands ###
