services:
  bot:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
      - ../alembic:/app/alembic
      - ../alembic.ini:/app/alembic.ini
      - ../logs:/app/logs
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    env_file:
      - ../.env
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT} --appendonly yes

  postgres:
    image: postgres:17
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  redis_data:
  pg_data: